# Generated by Django 3.2.12 on 2022-03-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_super_account_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
