# Generated by Django 3.2.12 on 2022-03-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_creation',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date_modification',
            new_name='modification_date',
        ),
    ]
