# Generated by Django 3.2.12 on 2022-03-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-category_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
